title: 胡洺滔的笔记
description: 个人笔记
url: "https://frankhumingtao.github.io"
baseurl: ""

remote_theme: just-the-docs/just-the-docs

color_scheme: light

# 搜索
search_enabled: true

# 辅助功能
aux_links:
  "GitHub":
    - "https://github.com/FrankHumingtao/FrankHumingtao.github.io"

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 集合
collections:
  pages:
    output: true
    permalink: /:collection/:path/

# 排除
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# 默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed
