title: Frank 的笔记本
description: 个人笔记
author: Frank
url: "https://frankhumingtao.github.io"
baseurl: ""

remote_theme: sighingnow/jekyll-gitbook

# 目录 (TOC)
toc:
  enabled: true
  h_min: 1
  h_max: 3

# Markdown 渲染
markdown: kramdown
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    guess_lang: true

syntax_highlighter_style: colorful

# 集合
collections:
  pages:
    output: true
    sort_by: date
    permalink: /:collection/:path/
  math:
    output: true
    permalink: /:collection/:path/
  ai:
    output: true
    permalink: /:collection/:path/
  drafts:
    output: true
    permalink: /:collection/:path/

ordered_collections:
  - pages
  - math
  - ai
  - drafts

page_width: 800px

destination: ./_site
incremental: false
regenerate: true

plugins:
  - jekyll-feed
  - jekyll-readme-index
  - jemoji

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

timezone: Asia/Shanghai
