title: 3mptywhite
description: 个人笔记
url: "https://3mptywhite.github.io"
baseurl: ""

remote_theme: just-the-docs/just-the-docs

color_scheme: custom

# 搜索
search_enabled: false

# 辅助功能
aux_links:
  "GitHub":
    - "https://github.com/3mptywhite"
  "知乎":
    - "https://www.zhihu.com/people/littlefat-17"
  "B站":
    - "https://space.bilibili.com/52475013"

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# 集合
collections:
  pages:
    output: true
    permalink: /:collection/:path/

# 排除
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# 默认布局
defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins:
  - jekyll-feed
